/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 13 15:31:34 GMT 2024
 */

package evosuite_1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import model.Loan;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Loan_ESTest extends Loan_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Loan loan0 = new Loan(0, 0, (LocalDate) null, 786.276F);
      loan0.getReturnDate();
      assertEquals(0, loan0.getBookCode());
      assertEquals(786.276F, loan0.getDailyFine(), 0.01F);
      assertEquals(0, loan0.getMemberId());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Loan loan0 = new Loan(0, 0, localDate0, 0);
      int int0 = loan0.getMemberId();
      assertEquals(0.0F, loan0.getDailyFine(), 0.01F);
      assertEquals(0, loan0.getBookCode());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Loan loan0 = new Loan(1736, 1736, localDate0, 1306.2784F);
      int int0 = loan0.getMemberId();
      assertEquals(1306.2784F, loan0.getDailyFine(), 0.01F);
      assertEquals(1736, loan0.getBookCode());
      assertEquals(1736, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Loan loan0 = new Loan(1736, 1736, localDate0, 1306.2784F);
      float float0 = loan0.getDailyFine();
      assertEquals(1306.2784F, float0, 0.01F);
      assertEquals(1736, loan0.getBookCode());
      assertEquals(1736, loan0.getMemberId());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-341L));
      Loan loan0 = new Loan((-1538), (-1538), localDate0, (-1.0F));
      float float0 = loan0.getDailyFine();
      assertEquals((-1.0F), float0, 0.01F);
      assertEquals((-1538), loan0.getBookCode());
      assertEquals((-1538), loan0.getMemberId());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Loan loan0 = new Loan(0, 0, (LocalDate) null, 0);
      int int0 = loan0.getBookCode();
      assertEquals(0, int0);
      assertEquals(0.0F, loan0.getDailyFine(), 0.01F);
      assertEquals(0, loan0.getMemberId());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Loan loan0 = new Loan(1736, 1736, localDate0, 1306.2784F);
      int int0 = loan0.getBookCode();
      assertEquals(1306.2784F, loan0.getDailyFine(), 0.01F);
      assertEquals(1736, int0);
      assertEquals(1736, loan0.getMemberId());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Loan loan0 = new Loan((-2910), (-2910), localDate0, 1608.7F);
      LocalDate localDate1 = MockLocalDate.ofEpochDay(751L);
      float float0 = loan0.calculateFine(localDate1);
      assertEquals((-2910), loan0.getBookCode());
      assertEquals(2.4716066E7F, float0, 0.01F);
      assertEquals((-2910), loan0.getMemberId());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Loan loan0 = new Loan(1736, 1736, localDate0, 1306.2784F);
      LocalDate localDate1 = MockLocalDate.ofEpochDay(1736);
      loan0.setReturnDate(localDate1);
      float float0 = loan0.calculateFine(localDate0);
      assertEquals(1736, loan0.getMemberId());
      assertEquals((-1.8782978E7F), float0, 0.01F);
      assertEquals(1736, loan0.getBookCode());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Loan loan0 = new Loan(0, 0, (LocalDate) null, 0);
      // Undeclared exception!
      try { 
        loan0.calculateFine((LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.time.temporal.ChronoUnit", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-341L));
      Loan loan0 = new Loan((-1538), (-1538), localDate0, (-1.0F));
      int int0 = loan0.getBookCode();
      assertEquals((-1538), int0);
      assertEquals((-1.0F), loan0.getDailyFine(), 0.01F);
      assertEquals((-1538), loan0.getMemberId());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-341L));
      Loan loan0 = new Loan((-1538), (-1538), localDate0, (-1.0F));
      loan0.extendLoan(localDate0);
      assertEquals((-1.0F), loan0.getDailyFine(), 0.01F);
      assertEquals((-1538), loan0.getMemberId());
      assertEquals((-1538), loan0.getBookCode());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-341L));
      Loan loan0 = new Loan((-1538), (-1538), localDate0, (-1.0F));
      int int0 = loan0.getMemberId();
      assertEquals((-1538), int0);
      assertEquals((-1538), loan0.getBookCode());
      assertEquals((-1.0F), loan0.getDailyFine(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-341L));
      Loan loan0 = new Loan((-1538), (-1538), localDate0, (-1.0F));
      float float0 = loan0.calculateFine(localDate0);
      assertEquals((-1538), loan0.getMemberId());
      assertEquals(-0.0F, float0, 0.01F);
      assertEquals((-1538), loan0.getBookCode());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-341L));
      Loan loan0 = new Loan((-1538), (-1538), localDate0, (-1.0F));
      loan0.getReturnDate();
      assertEquals((-1.0F), loan0.getDailyFine(), 0.01F);
      assertEquals((-1538), loan0.getBookCode());
      assertEquals((-1538), loan0.getMemberId());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Loan loan0 = new Loan(0, 0, localDate0, 0);
      float float0 = loan0.getDailyFine();
      assertEquals(0.0F, float0, 0.01F);
      assertEquals(0, loan0.getBookCode());
      assertEquals(0, loan0.getMemberId());
  }
}
