/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 13 15:31:47 GMT 2024
 */

package evosuite_1;

import org.junit.Test;
import static org.junit.Assert.*;
import model.Member;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Member_ESTest extends Member_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Member member0 = new Member(0, (String) null);
      member0.toString();
      assertEquals(0, member0.getId());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Member member0 = new Member(0, "IKF+Pb`gdb");
      member0.toString();
      assertEquals(0, member0.getId());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Member member0 = new Member(0, (String) null);
      member0.getName();
      assertEquals(0, member0.getId());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Member member0 = new Member(0, "IKF+Pb`gdb");
      member0.getName();
      assertEquals(0, member0.getId());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Member member0 = new Member(0, "IKF+Pb`gdb");
      int int0 = member0.getId();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Member member0 = new Member(1, "");
      int int0 = member0.getId();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Member member0 = new Member((-1015), "");
      member0.getName();
      assertEquals((-1015), member0.getId());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Member member0 = new Member((-1015), "");
      int int0 = member0.getId();
      assertEquals((-1015), int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Member member0 = new Member((-1015), "");
      member0.toString();
      assertEquals((-1015), member0.getId());
  }
}
