/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 13 15:42:12 GMT 2024
 */

package evosuite_3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import control.Library;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import java.util.ArrayList;
import model.Book;
import model.Loan;
import model.Member;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Library_ESTest extends Library_ESTest_scaffolding {

//  @Test(timeout = 4000)
//  public void test00()  throws Throwable  {
//      Library library0 = new Library();
//      library0.members = null;
//      ArrayList<Member> arrayList0 = library0.getMembers();
//      assertNull(arrayList0);
//  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Library library0 = new Library();
      ArrayList<Member> arrayList0 = new ArrayList<Member>();
      arrayList0.add((Member) null);
      library0.setMembers(arrayList0);
      ArrayList<Member> arrayList1 = library0.getMembers();
      assertEquals(1, arrayList1.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Library library0 = new Library();
      Book book0 = new Book("", "*Y\"o^%,$WW3c.GP!", 1207, 1207);
      Member member0 = new Member(1207, (String) null);
      Period period0 = Period.ZERO;
      IsoChronology isoChronology0 = period0.getChronology();
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
      library0.lendBook(book0, member0, localDate0);
      assertFalse(book0.isAvailable());
      
      LocalDate localDate1 = MockLocalDate.now();
      float float0 = library0.getMemberFine(member0, localDate1);
      assertEquals(60.350002F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Library library0 = new Library();
      Member member0 = new Member(0, "");
      LocalDate localDate0 = MockLocalDate.now();
      Book book0 = new Book("control.Library", "", (-2784), (-2784));
      library0.lendBook(book0, member0, localDate0);
      assertFalse(book0.isAvailable());
      
      LocalDate localDate1 = MockLocalDate.ofEpochDay(609L);
      float float0 = library0.getMemberFine(member0, localDate1);
      assertEquals((-2158435.2F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Library library0 = new Library();
      library0.setLoans((ArrayList<Loan>) null);
      ArrayList<Loan> arrayList0 = library0.getLoans();
      assertNull(arrayList0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Library library0 = new Library();
      Book book0 = new Book("", "", (-610), 0);
      Member member0 = new Member(0, "ZZp)H@ty\"g");
      library0.lendBook(book0, member0, (LocalDate) null);
      assertFalse(book0.isAvailable());
      
      ArrayList<Loan> arrayList0 = library0.getLoans();
      assertFalse(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Library library0 = new Library();
      LocalDate localDate0 = MockLocalDate.now();
      Loan loan0 = new Loan(4280, 4280, localDate0, 1023.82F);
      LocalDate localDate1 = MockLocalDate.ofEpochDay((-1270));
      double double0 = library0.getFineDiscount(loan0, localDate1);
      assertEquals(1.779489110085449E7, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Library library0 = new Library();
      library0.setBooks((ArrayList<Book>) null);
      ArrayList<Book> arrayList0 = library0.getBooks();
      assertNull(arrayList0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Library library0 = new Library();
      Book book0 = new Book("control.Library", "", (-2784), (-2784));
      library0.addBook(book0);
      ArrayList<Book> arrayList0 = library0.getBooks();
      assertTrue(arrayList0.contains(book0));
  }

//  @Test(timeout = 4000)
//  public void test09()  throws Throwable  {
//      Library library0 = new Library();
//      library0.members = null;
//      // Undeclared exception!
//      try {
//        library0.listAllMembers();
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("control.Library", e);
//      }
//  }

//  @Test(timeout = 4000)
//  public void test10()  throws Throwable  {
//      Library library0 = new Library();
//      library0.books = null;
//      // Undeclared exception!
//      try {
//        library0.listAllBooks();
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("control.Library", e);
//      }
//  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Library library0 = new Library();
      Member member0 = new Member((-3921), "");
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1273L);
      // Undeclared exception!
      try { 
        library0.lendBook((Book) null, member0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("control.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Library library0 = new Library();
      Period period0 = Period.ofDays(1);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Loan loan0 = new Loan(0, (-910), localDate0, 1);
      // Undeclared exception!
      try { 
        library0.getFineDiscount(loan0, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.time.temporal.ChronoUnit", e);
      }
  }

//  @Test(timeout = 4000)
//  public void test13()  throws Throwable  {
//      Library library0 = new Library();
//      library0.members = null;
//      Member member0 = new Member(0, "");
//      // Undeclared exception!
//      try {
//        library0.addMember(member0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("control.Library", e);
//      }
//  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Library library0 = new Library();
      library0.setBooks((ArrayList<Book>) null);
      // Undeclared exception!
      try { 
        library0.addBook((Book) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("control.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Library library0 = new Library();
      Book book0 = new Book("r9]=6O,Y", "", 320, 1497);
      Member member0 = new Member(1497, "");
      library0.lendBook(book0, member0, (LocalDate) null);
      // Undeclared exception!
      try { 
        library0.getMemberFine(member0, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.time.temporal.ChronoUnit", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Library library0 = new Library();
      LocalDate localDate0 = MockLocalDate.now();
      Book book0 = new Book("", "dTc@a86^-?u BdIr", 0, 0);
      Member member0 = new Member(0, "");
      book0.setAvailable(false);
      try { 
        library0.lendBook(book0, member0, localDate0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The requested book is currently unavailable.
         //
         verifyException("control.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Library library0 = new Library();
      library0.listAllBooks();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Library library0 = new Library();
      Member member0 = new Member(1497, "");
      float float0 = library0.getMemberFine(member0, (LocalDate) null);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Library library0 = new Library();
      ArrayList<Member> arrayList0 = library0.getMembers();
      library0.setMembers(arrayList0);
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Library library0 = new Library();
      library0.listAllMembers();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Library library0 = new Library();
      Period period0 = Period.ofDays(0);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Loan loan0 = new Loan(2268, 2268, localDate0, (-2842.927F));
      double double0 = library0.getFineDiscount(loan0, localDate0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Library library0 = new Library();
      Member member0 = new Member(0, "");
      library0.addMember(member0);
      assertEquals("", member0.toString());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Library library0 = new Library();
      ArrayList<Loan> arrayList0 = library0.getLoans();
      assertEquals(0, arrayList0.size());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Library library0 = new Library();
      ArrayList<Book> arrayList0 = library0.getBooks();
      library0.setBooks(arrayList0);
      assertEquals(0, arrayList0.size());
  }
}
