/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 13 15:38:05 GMT 2024
 */

package evosuite_2;

import org.junit.Test;
import static org.junit.Assert.*;
import model.Book;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Book_ESTest extends Book_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Book book0 = new Book(">c^d@kK>AtU?u}<j", (String) null, 2748, (-1629));
      assertTrue(book0.isAvailable());
      
      book0.setAvailable(false);
      boolean boolean0 = book0.isAvailable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Book book0 = new Book("", "", 0, 0);
      int int0 = book0.getValue();
      assertEquals(0, book0.getCode());
      assertTrue(book0.isAvailable());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Book book0 = new Book("", "I(yf3N|EL6fQ[<X-", 2142, 2142);
      int int0 = book0.getValue();
      assertTrue(book0.isAvailable());
      assertEquals(2142, int0);
      assertEquals(2142, book0.getCode());
      assertEquals("", book0.getTitle());
      assertEquals("I(yf3N|EL6fQ[<X-", book0.getAuthor());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Book book0 = new Book((String) null, "<Jx}LY$", (-1100), (-1100));
      String string0 = book0.getTitle();
      assertNull(string0);
      assertTrue(book0.isAvailable());
      assertEquals((-1100), book0.getValue());
      assertEquals((-1100), book0.getCode());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Book book0 = new Book("", "I(yf3N|EL6fQ[<X-", 2142, 2142);
      String string0 = book0.getTitle();
      assertEquals(2142, book0.getCode());
      assertEquals("I(yf3N|EL6fQ[<X-", book0.getAuthor());
      assertEquals(2142, book0.getValue());
      assertEquals("", string0);
      assertTrue(book0.isAvailable());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Book book0 = new Book("", "", 0, 0);
      int int0 = book0.getCode();
      assertTrue(book0.isAvailable());
      assertEquals(0, int0);
      assertEquals(0, book0.getValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Book book0 = new Book(">c^d@kK>AtU?u}<j", (String) null, 2748, (-1629));
      int int0 = book0.getCode();
      assertEquals((-1629), book0.getValue());
      assertTrue(book0.isAvailable());
      assertEquals(2748, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Book book0 = new Book(">c^d@kK>AtU?u}<j", (String) null, 2748, (-1629));
      String string0 = book0.getAuthor();
      assertNull(string0);
      assertEquals((-1629), book0.getValue());
      assertTrue(book0.isAvailable());
      assertEquals(2748, book0.getCode());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Book book0 = new Book("", "", (-481), (-481));
      book0.getAuthor();
      assertEquals((-481), book0.getCode());
      assertTrue(book0.isAvailable());
      assertEquals((-481), book0.getValue());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Book book0 = new Book("/N9[~HOWTBu", "/N9[~HOWTBu", (-1455), (-1455));
      int int0 = book0.getCode();
      assertTrue(book0.isAvailable());
      assertEquals((-1455), book0.getValue());
      assertEquals((-1455), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Book book0 = new Book("/N9[~HOWTBu", "/N9[~HOWTBu", (-1455), (-1455));
      String string0 = book0.toString();
      assertEquals((-1455), book0.getCode());
      assertEquals((-1455), book0.getValue());
      assertTrue(book0.isAvailable());
      assertEquals("/N9[~HOWTBu by /N9[~HOWTBU", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Book book0 = new Book("/N9[~HOWTBu", "/N9[~HOWTBu", (-1455), (-1455));
      book0.getAuthor();
      assertEquals((-1455), book0.getCode());
      assertTrue(book0.isAvailable());
      assertEquals((-1455), book0.getValue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Book book0 = new Book("/N9[~HOWTBu", "/N9[~HOWTBu", (-1455), (-1455));
      int int0 = book0.getValue();
      assertTrue(book0.isAvailable());
      assertEquals((-1455), int0);
      assertEquals((-1455), book0.getCode());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Book book0 = new Book("/N9[~HOWTBu", "/N9[~HOWTBu", (-1455), (-1455));
      book0.getTitle();
      assertEquals((-1455), book0.getValue());
      assertTrue(book0.isAvailable());
      assertEquals((-1455), book0.getCode());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Book book0 = new Book("/N9[~HOWTBu", "/N9[~HOWTBu", (-1455), (-1455));
      boolean boolean0 = book0.isAvailable();
      assertEquals((-1455), book0.getValue());
      assertEquals((-1455), book0.getCode());
      assertTrue(boolean0);
  }
}
