/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 13 15:36:45 GMT 2024
 */

package evosuite_2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import control.Library;
import java.time.Clock;
import java.time.LocalDate;
import java.time.Period;
import java.time.chrono.IsoChronology;
import java.util.ArrayList;
import model.Book;
import model.Loan;
import model.Member;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Library_ESTest extends Library_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Library library0 = new Library();
      library0.setMembers((ArrayList<Member>) null);
      ArrayList<Member> arrayList0 = library0.getMembers();
      assertNull(arrayList0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Library library0 = new Library();
      Member member0 = new Member(2010, "(DS8pY*+i:)");
      library0.addMember(member0);
      ArrayList<Member> arrayList0 = library0.getMembers();
      assertTrue(arrayList0.contains(member0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Library library0 = new Library();
      Book book0 = new Book("(DS8pY*+i:)", "(DS8pY*+i:)", 2010, 2010);
      Member member0 = new Member(2010, "(DS8pY*+i:)");
      LocalDate localDate0 = MockLocalDate.now();
      library0.lendBook(book0, member0, localDate0);
      assertFalse(book0.isAvailable());
      
      System.setCurrentTimeMillis(1);
      Period period0 = Period.ofWeeks(1);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate1 = MockIsoChronology.dateNow(isoChronology0);
      float float0 = library0.getMemberFine(member0, localDate1);
      assertEquals(1619557.5F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Library library0 = new Library();
      Book book0 = new Book("", "", (-956), (-956));
      Member member0 = new Member((-956), (String) null);
      LocalDate localDate0 = MockLocalDate.now();
      library0.lendBook(book0, member0, localDate0);
      assertFalse(book0.isAvailable());
      
      LocalDate localDate1 = MockLocalDate.ofEpochDay((-302L));
      float float0 = library0.getMemberFine(member0, localDate1);
      assertEquals((-784732.56F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Library library0 = new Library();
      library0.setLoans((ArrayList<Loan>) null);
      ArrayList<Loan> arrayList0 = library0.getLoans();
      assertNull(arrayList0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Library library0 = new Library();
      Book book0 = new Book("control.ibrar}", "control.ibrar}", (-2903), (-2903));
      Member member0 = new Member((-2903), "control.ibrar}");
      LocalDate localDate0 = MockLocalDate.now();
      library0.lendBook(book0, member0, localDate0);
      assertFalse(book0.isAvailable());
      
      ArrayList<Loan> arrayList0 = library0.getLoans();
      assertFalse(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Library library0 = new Library();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Loan loan0 = new Loan(711, 711, localDate0, 1.0F);
      LocalDate localDate1 = MockLocalDate.now();
      loan0.setReturnDate(localDate1);
      double double0 = library0.getFineDiscount(loan0, localDate0);
      assertEquals(15988.055130076084, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Library library0 = new Library();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1);
      Loan loan0 = new Loan(1, 1257, localDate0, 0.05F);
      System.setCurrentTimeMillis(1257);
      Period period0 = Period.ofWeeks(1298);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate1 = MockIsoChronology.dateNow(isoChronology0);
      double double0 = library0.getFineDiscount(loan0, localDate1);
      assertEquals((-0.17360679867092138), double0, 0.01);
  }

//  @Test(timeout = 4000)
//  public void test08()  throws Throwable  {
//      Library library0 = new Library();
//      library0.books = null;
//      ArrayList<Book> arrayList0 = library0.getBooks();
//      assertNull(arrayList0);
//  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Library library0 = new Library();
      Book book0 = new Book("KI>I3ZPnVJa<", "Ac7UHaRUqbQ", 0, 0);
      library0.addBook(book0);
      ArrayList<Book> arrayList0 = library0.getBooks();
      assertTrue(arrayList0.contains(book0));
  }

//  @Test(timeout = 4000)
//  public void test10()  throws Throwable  {
//      Library library0 = new Library();
//      library0.members = null;
//      // Undeclared exception!
//      try {
//        library0.listAllMembers();
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("control.Library", e);
//      }
//  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Library library0 = new Library();
      library0.setBooks((ArrayList<Book>) null);
      // Undeclared exception!
      try { 
        library0.listAllBooks();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("control.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Library library0 = new Library();
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      library0.setLoans((ArrayList<Loan>) null);
      Member member0 = new Member(1234, "model.Loan");
      // Undeclared exception!
      try { 
        library0.getMemberFine(member0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("control.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Library library0 = new Library();
      // Undeclared exception!
      try { 
        library0.getFineDiscount((Loan) null, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("control.Library", e);
      }
  }

//  @Test(timeout = 4000)
//  public void test14()  throws Throwable  {
//      Library library0 = new Library();
//      Member member0 = new Member(0, "");
//      library0.members = null;
//      // Undeclared exception!
//      try {
//        library0.addMember(member0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("control.Library", e);
//      }
//  }

//  @Test(timeout = 4000)
//  public void test15()  throws Throwable  {
//      Library library0 = new Library();
//      library0.books = null;
//      Book book0 = new Book("control.Library", "", (-3663), (-1));
//      // Undeclared exception!
//      try {
//        library0.addBook(book0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("control.Library", e);
//      }
//  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Library library0 = new Library();
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Book book0 = new Book(",5D],g>t\"Zch69{R", "", 828, 0);
      // Undeclared exception!
      try { 
        library0.lendBook(book0, (Member) null, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("control.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Library library0 = new Library();
      Member member0 = new Member(596, "");
      Book book0 = new Book("KI>I3ZPnVJa<", "Ac7UHaRUqbQ", 0, 0);
      book0.setAvailable(false);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1035L);
      try { 
        library0.lendBook(book0, member0, localDate0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The requested book is currently unavailable.
         //
         verifyException("control.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Library library0 = new Library();
      library0.listAllBooks();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Library library0 = new Library();
      Member member0 = new Member(0, "");
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      float float0 = library0.getMemberFine(member0, localDate0);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Library library0 = new Library();
      ArrayList<Member> arrayList0 = library0.getMembers();
      library0.setMembers(arrayList0);
      assertEquals(0, arrayList0.size());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Library library0 = new Library();
      library0.listAllMembers();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Library library0 = new Library();
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Loan loan0 = new Loan(0, 0, localDate0, 0);
      double double0 = library0.getFineDiscount(loan0, localDate0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Library library0 = new Library();
      ArrayList<Loan> arrayList0 = library0.getLoans();
      library0.setLoans(arrayList0);
      assertEquals(0, arrayList0.size());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Library library0 = new Library();
      ArrayList<Book> arrayList0 = library0.getBooks();
      library0.setBooks(arrayList0);
      assertTrue(arrayList0.isEmpty());
  }
}
