/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 13 15:38:28 GMT 2024
 */

package evosuite_2;

import org.junit.Test;
import static org.junit.Assert.*;
import model.Member;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Member_ESTest extends Member_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Member member0 = new Member(1, (String) null);
      member0.toString();
      assertEquals(1, member0.getId());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Member member0 = new Member(2907, "(,.2[");
      member0.toString();
      assertEquals(2907, member0.getId());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Member member0 = new Member(1, (String) null);
      member0.getName();
      assertEquals(1, member0.getId());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Member member0 = new Member(0, "");
      member0.getName();
      assertEquals(0, member0.getId());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Member member0 = new Member(0, "");
      int int0 = member0.getId();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Member member0 = new Member(1, (String) null);
      int int0 = member0.getId();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Member member0 = new Member((-1), "-6w");
      member0.getName();
      assertEquals((-1), member0.getId());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Member member0 = new Member((-1), "");
      int int0 = member0.getId();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Member member0 = new Member((-1), "");
      member0.toString();
      assertEquals((-1), member0.getId());
  }
}
